services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6001:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: spyal
      POSTGRES_PASSWORD: spyalpassword
      POSTGRES_DB: spyaldb
    ports:
      - "6000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spyal -d spyaldb"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  spyal:
    image: spyal
    container_name: spyal
    build: .
    env_file:
      - .env.production
    ports:
      - "8080:8080"
    volumes:
      - /var/log/alspy.log:/var/log/alspy.log
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
