services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  alspy:
    image: alspy
    container_name: alspy
    build: .
    env_file:
      - .env.production
    ports:
      - "8080:8080"
    volumes:
      - /var/log/alspy.log:/var/log/alspy.log
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis_data:
